export default {
  "/mograph": "/motion",
  "/editingreel": "https://youtu.be/GM1dctHM1EM",
  "/videography": "https://vimeo.com/1123610282?share=copy",
  "/frontier": "https://youtu.be/GM1dctHM1EM",
  "/capturereel": "/capture",
  "/mographreel": "https://www.youtube.com/watch?v=ak7QmAedl2k",
  "/cv": "/data/CV.pdf",
  "/pages/notionclock": "/notionclock",
  "/projects/notionclock": "/notionclock",
  "/alison": "https://drive.google.com/drive/folders/1W06JYY5sLY74p2img5pADk7MFYNNTY6v?usp=sharing",
  "/project/arid": "/project/planetzoo#arid",
  "/project/oceania": "/project/planetzoo#oceania",
  "/project/malta": "/project/jwe2#malta",
  "/project/biosyn": "/project/jwe2#biosyn",
  "/project/lateCretaceous": "/project/jwe2#lateCretaceous",
  "/project/campCretaceous": "/project/jwe2#campCretaceous",
  "/project/earlyCretaceous": "/project/jwe2#earlyCretaceous",
  "/project/military": "/project/stranded#military",
  "/project/robots": "/project/stranded#robots",
  "/project/preorder": "/project/stranded#preorder",
};