[build]
command = "bun run build"
publish = "build"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/mograph"
  to = "/motion"
  status = 301

[[redirects]]
  from = "/editingreel"
  to = "https://youtu.be/GM1dctHM1EM"
  status = 301

[[redirects]]
  from = "/videography"
  to = "https://vimeo.com/1123610282?share=copy"
  status = 301

[[redirects]]
  from = "/frontier"
  to = "https://youtu.be/GM1dctHM1EM"
  status = 301

[[redirects]]
  from = "/capturereel"
  to = "/capture"
  status = 301

[[redirects]]
  from = "/mographreel"
  to = "https://www.youtube.com/watch?v=ak7QmAedl2k"
  status = 301

[[redirects]]
  from = "/cv"
  to = "/data/CV.pdf"
  status = 301

[[redirects]]
  from = "/pages/notionclock"
  to = "/notionclock"
  status = 301

[[redirects]]
  from = "/projects/notionclock"
  to = "/notionclock"
  status = 301

[[redirects]]
  from = "/alison"
  to = "https://drive.google.com/drive/folders/1W06JYY5sLY74p2img5pADk7MFYNNTY6v?usp=sharing"
  status = 301

[[redirects]]
  from = "/project/arid"
  to = "/project/planetzoo#arid"
  status = 301

[[redirects]]
  from = "/project/oceania"
  to = "/project/planetzoo#oceania"
  status = 301

[[redirects]]
  from = "/project/malta"
  to = "/project/jwe2#malta"
  status = 301

[[redirects]]
  from = "/project/biosyn"
  to = "/project/jwe2#biosyn"
  status = 301

[[redirects]]
  from = "/project/lateCretaceous"
  to = "/project/jwe2#lateCretaceous"
  status = 301

[[redirects]]
  from = "/project/campCretaceous"
  to = "/project/jwe2#campCretaceous"
  status = 301

[[redirects]]
  from = "/project/earlyCretaceous"
  to = "/project/jwe2#earlyCretaceous"
  status = 301

[[redirects]]
  from = "/project/military"
  to = "/project/stranded#military"
  status = 301

[[redirects]]
  from = "/project/robots"
  to = "/project/stranded#robots"
  status = 301

[[redirects]]
  from = "/project/preorder"
  to = "/project/stranded#preorder"
  status = 301

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
